# Postgresql
development:
  adapter: postgresql
  database: mugshot
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: mugshot
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mugshot
  host: localhost
  pool: 5
  timeout: 5000
