# Postgresql
development:
  adapter: postgresql
  encoding: unicode
  database: mugshots
  host: localhost
  username: garethadavies
  password: postgresql

test:
  adapter: postgresql
  encoding: unicode
  database: mugshots
  host: localhost
  username: postgresql

production:
  adapter: postgresql
  encoding: unicode
  database: mugshots
