# Postgresql
development:
  adapter: postgresql
  encoding: unicode
  database: mugshots
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: mugshots
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: mugshots
  host: localhost
  pool: 5
  timeout: 5000
